<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"; "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Zend Framework Default Application</title>
</head>
<body>
    <h3 style="color:red">Ошибка приложения! <?php echo $this->message ?></h3>

<?php if ('development' == $this->env): ?>

<h3>Exception information:</h3>

<h3>Stack trace:</h3>
<pre><?php echo $this->exception->getTraceAsString() ?> 
  </pre>

<h3>Request Parameters:</h3>
<pre><?php var_dump($this->request->getParams()) ?>
  </pre>

<p><b>Message:</b> <?php echo $this->exception->getMessage() ?></p>

<?php endif ?>

</body>
</html>
